#!/usr/bin/env bash

if [ "$1" == "install" ]; then
    wget -q https://mirror.olnevhost.net/pub/apache/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
    tar -xzf apache-maven-3.8.3-bin.tar.gz
    rm apache-maven-3.8.3-bin.tar.gz
    apache-maven-3.8.3/bin/mvn -q -f app/ clean install
    echo "1 dependency installed..."
    exit 0

else 
    java -jar app/target/app-1.0-SNAPSHOT.jar $1
    exit $?
fi